// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package grpcsrv

import (
	"context"
	"github.com/57blocks/go-boilerplate/internal/server/echo"
	"google.golang.org/grpc"
)

// Injectors from inject_local.go:

func SetupLocal(ctx context.Context) (*grpc.Server, func(), error) {
	echoServiceServer := echo.New()
	grpcsrvServices := &services{
		echo: echoServiceServer,
	}
	server := newGrpcServer(grpcsrvServices)
	return server, func() {
	}, nil
}
